/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.polystorage.view;

import com.polystorage.entity.NhanVien;
import com.polystorage.helper.DialogHelper;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Long
 */
public class MainFrame extends javax.swing.JFrame {

    public static NhanVien nhanVien = null;
    boolean isNhanVien = true;

    /**
     * Creates new form Homepagenew
     */
    public MainFrame() {
        new JDialogChao(this, true).setVisible(true);
        new JDialogLogin(this, true).setVisible(true);
        if (nhanVien.getVaiTro().equals("Trưởng Phòng")) {
            isNhanVien = false;
        }
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        reloadRootPanel(new PanelDanhSachDonNhap(isNhanVien));
        
        //lblNhanVien.setText(nhanVien.getVaiTro() + ": " + nhanVien.getHoTen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlQuanLyDonHang = new javax.swing.JPanel();
        pnlDonNhap = new javax.swing.JPanel();
        btnDonNhap = new javax.swing.JLabel();
        pnlDonXuat = new javax.swing.JPanel();
        btnDonXuat = new javax.swing.JLabel();
        pnlQuanLyKhac = new javax.swing.JPanel();
        pnlNhaCungCap = new javax.swing.JPanel();
        btnNhaCungCap = new javax.swing.JLabel();
        pnlKhachHang = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JLabel();
        pnlSanPham = new javax.swing.JPanel();
        btnSanPham = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        btnTongSanPhamNhapXuat = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        btnTonKho = new javax.swing.JLabel();
        pnlRoot = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 102, 255));

        pnlQuanLyDonHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Đơn Hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        pnlDonNhap.setBackground(new java.awt.Color(35, 124, 196));

        btnDonNhap.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDonNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDonNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDonNhap.setText("Đơn Nhập");
        btnDonNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonNhapMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDonNhapLayout = new javax.swing.GroupLayout(pnlDonNhap);
        pnlDonNhap.setLayout(pnlDonNhapLayout);
        pnlDonNhapLayout.setHorizontalGroup(
            pnlDonNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDonNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlDonNhapLayout.setVerticalGroup(
            pnlDonNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDonNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlQuanLyDonHang.add(pnlDonNhap);

        pnlDonXuat.setBackground(new java.awt.Color(35, 124, 196));

        btnDonXuat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDonXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDonXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDonXuat.setText("Đơn Xuất");
        btnDonXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDonXuatLayout = new javax.swing.GroupLayout(pnlDonXuat);
        pnlDonXuat.setLayout(pnlDonXuatLayout);
        pnlDonXuatLayout.setHorizontalGroup(
            pnlDonXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDonXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlDonXuatLayout.setVerticalGroup(
            pnlDonXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDonXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlQuanLyDonHang.add(pnlDonXuat);

        pnlQuanLyKhac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Khác", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        pnlNhaCungCap.setBackground(new java.awt.Color(35, 124, 196));

        btnNhaCungCap.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnNhaCungCap.setForeground(new java.awt.Color(255, 255, 255));
        btnNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNhaCungCap.setText("Nhà Cung Cấp");
        btnNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhaCungCapMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNhaCungCapLayout = new javax.swing.GroupLayout(pnlNhaCungCap);
        pnlNhaCungCap.setLayout(pnlNhaCungCapLayout);
        pnlNhaCungCapLayout.setHorizontalGroup(
            pnlNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlNhaCungCapLayout.setVerticalGroup(
            pnlNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlQuanLyKhac.add(pnlNhaCungCap);

        pnlKhachHang.setBackground(new java.awt.Color(35, 124, 196));

        btnKhachHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlQuanLyKhac.add(pnlKhachHang);

        pnlSanPham.setBackground(new java.awt.Color(35, 124, 196));

        btnSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlQuanLyKhac.add(pnlSanPham);

        pnlNhanVien.setBackground(new java.awt.Color(35, 124, 196));

        btnNhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlQuanLyKhac.add(pnlNhanVien);

        pnlThongKe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống Kê", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel16.setBackground(new java.awt.Color(35, 124, 196));

        btnTongSanPhamNhapXuat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnTongSanPhamNhapXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnTongSanPhamNhapXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTongSanPhamNhapXuat.setText("Nhập Xuất");
        btnTongSanPhamNhapXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTongSanPhamNhapXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTongSanPhamNhapXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTongSanPhamNhapXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTongSanPhamNhapXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlThongKe.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(35, 124, 196));

        btnTonKho.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnTonKho.setForeground(new java.awt.Color(255, 255, 255));
        btnTonKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTonKho.setText("Tồn Kho");
        btnTonKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTonKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTonKhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTonKho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlThongKe.add(jPanel17);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlQuanLyDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlQuanLyKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlQuanLyDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlQuanLyKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pnlRoot.setLayout(new java.awt.GridLayout(1, 0));

        pnlLogo.setBackground(new java.awt.Color(51, 85, 193));

        lblLogo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setText("POLY STORAGE");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonNhapMouseClicked
        reloadRootPanel(new PanelDanhSachDonNhap(isNhanVien));
    }//GEN-LAST:event_btnDonNhapMouseClicked

    private void btnNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaCungCapMouseClicked
        reloadRootPanel(new PanelDanhSachNhaCungCap(isNhanVien));
    }//GEN-LAST:event_btnNhaCungCapMouseClicked

    private void btnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseClicked
        reloadRootPanel(new PanelDanhSachKhachHang(isNhanVien));
    }//GEN-LAST:event_btnKhachHangMouseClicked

    private void btnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamMouseClicked
        reloadRootPanel(new PanelDanhSachSanPham(isNhanVien));
    }//GEN-LAST:event_btnSanPhamMouseClicked

    private void btnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseClicked
        if (isNhanVien){
            DialogHelper.showMessageDialog(null, "Bạn không có quyền truy cập");
        } else {
            reloadRootPanel(new PanelDanhSachNhanVien(isNhanVien));
        }
    }//GEN-LAST:event_btnNhanVienMouseClicked

    private void btnDonXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonXuatMouseClicked
        reloadRootPanel(new PanelDanhSachDonXuat(isNhanVien));
    }//GEN-LAST:event_btnDonXuatMouseClicked

    private void btnTongSanPhamNhapXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTongSanPhamNhapXuatMouseClicked
        reloadRootPanel(new PanelTongSanPhamNhapXuat(isNhanVien));
    }//GEN-LAST:event_btnTongSanPhamNhapXuatMouseClicked

    private void btnTonKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTonKhoMouseClicked
        reloadRootPanel(new PanelHangTonKho());
    }//GEN-LAST:event_btnTonKhoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDonNhap;
    private javax.swing.JLabel btnDonXuat;
    private javax.swing.JLabel btnKhachHang;
    private javax.swing.JLabel btnNhaCungCap;
    private javax.swing.JLabel btnNhanVien;
    private javax.swing.JLabel btnSanPham;
    private javax.swing.JLabel btnTonKho;
    private javax.swing.JLabel btnTongSanPhamNhapXuat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlDonNhap;
    private javax.swing.JPanel pnlDonXuat;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlNhaCungCap;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlQuanLyDonHang;
    private javax.swing.JPanel pnlQuanLyKhac;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlThongKe;
    // End of variables declaration//GEN-END:variables
    private void reloadRootPanel(JPanel panel) {
        pnlRoot.removeAll();
        pnlRoot.add(panel);
        pnlRoot.updateUI();
    }
}
