package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1



/**
 * ChitietdonxuatId generated by hbm2java
 */
public class ChiTietDonXuatId  implements java.io.Serializable {


     private int maDX;
     private String maSP;

    public ChiTietDonXuatId() {
    }

    public ChiTietDonXuatId(int maDx, String maSp) {
       this.maDX = maDx;
       this.maSP = maSp;
    }
   
    public int getMaDX() {
        return this.maDX;
    }
    
    public void setMaDX(int maDx) {
        this.maDX = maDx;
    }
    public String getMaSP() {
        return this.maSP;
    }
    
    public void setMaSP(String maSp) {
        this.maSP = maSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChiTietDonXuatId) ) return false;
		 ChiTietDonXuatId castOther = ( ChiTietDonXuatId ) other; 
         
		 return (this.getMaDX()==castOther.getMaDX())
 && ( (this.getMaSP()==castOther.getMaSP()) || ( this.getMaSP()!=null && castOther.getMaSP()!=null && this.getMaSP().equals(castOther.getMaSP()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMaDX();
         result = 37 * result + ( getMaSP() == null ? 0 : this.getMaSP().hashCode() );
         return result;
   }   


}


