package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1



/**
 * Chitietkho generated by hbm2java
 */
public class ChiTietKho  implements java.io.Serializable {


     private ChiTietKhoId id;
     private Kho kho;
     private SanPham sanPham;
     private int soLuong;

    public ChiTietKho() {
    }

    public ChiTietKho(ChiTietKhoId id, Kho kho, SanPham sanpham, int soLuong) {
       this.id = id;
       this.kho = kho;
       this.sanPham = sanpham;
       this.soLuong = soLuong;
    }
   
    public ChiTietKhoId getId() {
        return this.id;
    }
    
    public void setId(ChiTietKhoId id) {
        this.id = id;
    }
    public Kho getKho() {
        return this.kho;
    }
    
    public void setKho(Kho kho) {
        this.kho = kho;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanpham) {
        this.sanPham = sanpham;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }




}


