package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1



/**
 * ChitietkhoId generated by hbm2java
 */
public class ChiTietKhoId  implements java.io.Serializable {


     private String maKho;
     private String maSP;

    public ChiTietKhoId() {
    }

    public ChiTietKhoId(String maKho, String maSp) {
       this.maKho = maKho;
       this.maSP = maSp;
    }
   
    public String getMaKho() {
        return this.maKho;
    }
    
    public void setMaKho(String maKho) {
        this.maKho = maKho;
    }
    public String getMaSp() {
        return this.maSP;
    }
    
    public void setMaSp(String maSp) {
        this.maSP = maSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChiTietKhoId) ) return false;
		 ChiTietKhoId castOther = ( ChiTietKhoId ) other; 
         
		 return ( (this.getMaKho()==castOther.getMaKho()) || ( this.getMaKho()!=null && castOther.getMaKho()!=null && this.getMaKho().equals(castOther.getMaKho()) ) )
 && ( (this.getMaSp()==castOther.getMaSp()) || ( this.getMaSp()!=null && castOther.getMaSp()!=null && this.getMaSp().equals(castOther.getMaSp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaKho() == null ? 0 : this.getMaKho().hashCode() );
         result = 37 * result + ( getMaSp() == null ? 0 : this.getMaSp().hashCode() );
         return result;
   }   


}


