package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donxuat generated by hbm2java
 */
public class DonXuat implements java.io.Serializable {

    private Integer maDX;
    private KhachHang khachHang;
    private Kho kho;
    private NhanVien nhanVien;
    private Date ngayXuat;
    private boolean trangThai;
    private Set chiTietDonXuats = new HashSet(0);

    public DonXuat() {
    }

    public DonXuat(KhachHang khachhang, Kho kho, NhanVien nhanvien, Date ngayXuat, boolean trangThai) {
        this.khachHang = khachhang;
        this.kho = kho;
        this.nhanVien = nhanvien;
        this.ngayXuat = ngayXuat;
        this.trangThai = trangThai;
    }

    public DonXuat(KhachHang khachhang, Kho kho, NhanVien nhanvien, Date ngayXuat, boolean trangThai, Set chitietdonxuats) {
        this.khachHang = khachhang;
        this.kho = kho;
        this.nhanVien = nhanvien;
        this.ngayXuat = ngayXuat;
        this.trangThai = trangThai;
        this.chiTietDonXuats = chitietdonxuats;
    }

    public Integer getMaDX() {
        return maDX;
    }

    public void setMaDX(Integer maDX) {
        this.maDX = maDX;
    }

    public KhachHang getKhachHang() {
        return khachHang;
    }

    public void setKhachHang(KhachHang khachHang) {
        this.khachHang = khachHang;
    }

    public Kho getKho() {
        return kho;
    }

    public void setKho(Kho kho) {
        this.kho = kho;
    }

    public NhanVien getNhanVien() {
        return nhanVien;
    }

    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }

    public Date getNgayXuat() {
        return ngayXuat;
    }

    public void setNgayXuat(Date ngayXuat) {
        this.ngayXuat = ngayXuat;
    }

    public boolean isTrangThai() {
        return trangThai;
    }

    public void setTrangThai(boolean trangThai) {
        this.trangThai = trangThai;
    }

    public Set getChiTietDonXuats() {
        return chiTietDonXuats;
    }

    public void setChiTietDonXuats(Set chiTietDonXuats) {
        this.chiTietDonXuats = chiTietDonXuats;
    }

}
