package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class KhachHang  implements java.io.Serializable {


     private String maKH;
     private String hoTen;
     private String email;
     private String sdt;
     private String diaChi;
     private String ghiChu;
     private Set donXuats = new HashSet(0);

    public KhachHang() {
    }

	
    public KhachHang(String maKh, String hoTen, String email, String sdt, String diaChi) {
        this.maKH = maKh;
        this.hoTen = hoTen;
        this.email = email;
        this.sdt = sdt;
        this.diaChi = diaChi;
    }
    public KhachHang(String maKh, String hoTen, String email, String sdt, String diaChi, String ghiChu, Set donxuats) {
       this.maKH = maKh;
       this.hoTen = hoTen;
       this.email = email;
       this.sdt = sdt;
       this.diaChi = diaChi;
       this.ghiChu = ghiChu;
       this.donXuats = donxuats;
    }

    public String getMaKH() {
        return maKH;
    }

    public void setMaKH(String maKH) {
        this.maKH = maKH;
    }

    public String getHoTen() {
        return hoTen;
    }

    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSdt() {
        return sdt;
    }

    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    public String getDiaChi() {
        return diaChi;
    }

    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    public String getGhiChu() {
        return ghiChu;
    }

    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }

    public Set getDonXuats() {
        return donXuats;
    }

    public void setDonXuats(Set donXuats) {
        this.donXuats = donXuats;
    }
   
    
}


