package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kho generated by hbm2java
 */
public class Kho  implements java.io.Serializable {


     private String maKho;
     private String diaChi;
     private Set donnhaps = new HashSet(0);
     private Set chitietkhos = new HashSet(0);
     private Set donxuats = new HashSet(0);

    public Kho() {
    }

	
    public Kho(String maKho, String diaChi) {
        this.maKho = maKho;
        this.diaChi = diaChi;
    }
    public Kho(String maKho, String diaChi, Set donnhaps, Set chitietkhos, Set donxuats) {
       this.maKho = maKho;
       this.diaChi = diaChi;
       this.donnhaps = donnhaps;
       this.chitietkhos = chitietkhos;
       this.donxuats = donxuats;
    }
   
    public String getMaKho() {
        return this.maKho;
    }
    
    public void setMaKho(String maKho) {
        this.maKho = maKho;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Set getDonnhaps() {
        return this.donnhaps;
    }
    
    public void setDonnhaps(Set donnhaps) {
        this.donnhaps = donnhaps;
    }
    public Set getChitietkhos() {
        return this.chitietkhos;
    }
    
    public void setChitietkhos(Set chitietkhos) {
        this.chitietkhos = chitietkhos;
    }
    public Set getDonxuats() {
        return this.donxuats;
    }
    
    public void setDonxuats(Set donxuats) {
        this.donxuats = donxuats;
    }




}


