package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Loaisanpham generated by hbm2java
 */
public class LoaiSanPham implements java.io.Serializable {

    private String maLoai;
    private String tenLoai;
    private Set sanPhams = new HashSet(0);

    public LoaiSanPham() {
    }

    public String getMaLoai() {
        return maLoai;
    }

    public void setMaLoai(String maLoai) {
        this.maLoai = maLoai;
    }

    public String getTenLoai() {
        return tenLoai;
    }

    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }

    public Set getSanPhams() {
        return sanPhams;
    }

    public void setSanPhams(Set sanPhams) {
        this.sanPhams = sanPhams;
    }

}
