package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class NhaCungCap implements java.io.Serializable {

    private String maNCC;
    private String tenNCC;
    private String email;
    private String sdt;
    private String diaChi;
    private String ghiChu;
    private Set sanPhams = new HashSet(0);
    private Set donNhaps = new HashSet(0);

    public NhaCungCap() {
    }

    public NhaCungCap(String maNcc, String tenNcc, String email, String sdt, String diaChi) {
        this.maNCC = maNcc;
        this.tenNCC = tenNcc;
        this.email = email;
        this.sdt = sdt;
        this.diaChi = diaChi;
    }

    public NhaCungCap(String maNcc, String tenNcc, String email, String sdt, String diaChi, String ghiChu, Set sanphams, Set donnhaps) {
        this.maNCC = maNcc;
        this.tenNCC = tenNcc;
        this.email = email;
        this.sdt = sdt;
        this.diaChi = diaChi;
        this.ghiChu = ghiChu;
        this.sanPhams = sanphams;
        this.donNhaps = donnhaps;
    }

    public String getMaNCC() {
        return maNCC;
    }

    public void setMaNCC(String maNCC) {
        this.maNCC = maNCC;
    }

    public String getTenNCC() {
        return tenNCC;
    }

    public void setTenNCC(String tenNCC) {
        this.tenNCC = tenNCC;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSdt() {
        return sdt;
    }

    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    public String getDiaChi() {
        return diaChi;
    }

    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    public String getGhiChu() {
        return ghiChu;
    }

    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }

    public Set getSanPhams() {
        return sanPhams;
    }

    public void setSanPhams(Set sanPhams) {
        this.sanPhams = sanPhams;
    }

    public Set getDonNhaps() {
        return donNhaps;
    }

    public void setDonNhaps(Set donNhaps) {
        this.donNhaps = donNhaps;
    }

}
