package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class NhanVien  implements java.io.Serializable {


     private String maNv;
     private String hoTen;
     private String email;
     private boolean gioiTinh;
     private String sdt;
     private String matKhau;
     private String hinh;
     private String vaiTro;
     private Set donNhaps = new HashSet(0);
     private Set donXuats = new HashSet(0);

    public NhanVien() {
    }

	
    public NhanVien(String maNv, String hoTen, String email, boolean gioiTinh, String sdt, String matKhau, String hinh, String vaiTro) {
        this.maNv = maNv;
        this.hoTen = hoTen;
        this.email = email;
        this.gioiTinh = gioiTinh;
        this.sdt = sdt;
        this.matKhau = matKhau;
        this.hinh = hinh;
        this.vaiTro = vaiTro;
    }
    public NhanVien(String maNv, String hoTen, String email, boolean gioiTinh, String sdt, String matKhau, String hinh, String vaiTro, Set donnhaps, Set donxuats) {
       this.maNv = maNv;
       this.hoTen = hoTen;
       this.email = email;
       this.gioiTinh = gioiTinh;
       this.sdt = sdt;
       this.matKhau = matKhau;
       this.hinh = hinh;
       this.vaiTro = vaiTro;
       this.donNhaps = donnhaps;
       this.donXuats = donxuats;
    }
   
    public String getMaNv() {
        return this.maNv;
    }
    
    public void setMaNv(String maNv) {
        this.maNv = maNv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getHinh() {
        return this.hinh;
    }
    
    public void setHinh(String hinh) {
        this.hinh = hinh;
    }
    public String getVaiTro() {
        return this.vaiTro;
    }
    
    public void setVaiTro(String vaiTro) {
        this.vaiTro = vaiTro;
    }
    public Set getDonnhaps() {
        return this.donNhaps;
    }
    
    public void setDonnhaps(Set donnhaps) {
        this.donNhaps = donnhaps;
    }
    public Set getDonxuats() {
        return this.donXuats;
    }
    
    public void setDonxuats(Set donxuats) {
        this.donXuats = donxuats;
    }




}


