package com.polystorage.entity;
// Generated Nov 22, 2019 11:47:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Sanpham generated by hbm2java
 */
public class SanPham implements java.io.Serializable {

    private String maSp;
    private LoaiSanPham loaiSanPham;
    private NhaCungCap nhaCungCap;
    private String tenSp;
    private String donViTinh;
    private float giaDv;
    private Set chiTietDonXuats = new HashSet(0);
    private Set chiTietKhos = new HashSet(0);
    private Set chiTietDonNhaps = new HashSet(0);

    public SanPham() {
    }

    public SanPham(String maSp, LoaiSanPham loaisanpham, NhaCungCap nhacungcap, String tenSp, String donViTinh, float giaDv) {
        this.maSp = maSp;
        this.loaiSanPham = loaisanpham;
        this.nhaCungCap = nhacungcap;
        this.tenSp = tenSp;
        this.donViTinh = donViTinh;
        this.giaDv = giaDv;
    }

    public SanPham(String maSp, LoaiSanPham loaisanpham, NhaCungCap nhacungcap, String tenSp, String donViTinh, float giaDv, Set chitietdonxuats, Set chitietkhos, Set chitietdonnhaps) {
        this.maSp = maSp;
        this.loaiSanPham = loaisanpham;
        this.nhaCungCap = nhacungcap;
        this.tenSp = tenSp;
        this.donViTinh = donViTinh;
        this.giaDv = giaDv;
        this.chiTietDonXuats = chitietdonxuats;
        this.chiTietKhos = chitietkhos;
        this.chiTietDonNhaps = chitietdonnhaps;
    }

    public String getMaSp() {
        return maSp;
    }

    public void setMaSp(String maSp) {
        this.maSp = maSp;
    }

    public LoaiSanPham getLoaiSanPham() {
        return loaiSanPham;
    }

    public void setLoaiSanPham(LoaiSanPham loaiSanPham) {
        this.loaiSanPham = loaiSanPham;
    }

    public NhaCungCap getNhaCungCap() {
        return nhaCungCap;
    }

    public void setNhaCungCap(NhaCungCap nhaCungCap) {
        this.nhaCungCap = nhaCungCap;
    }

    public String getTenSp() {
        return tenSp;
    }

    public void setTenSp(String tenSp) {
        this.tenSp = tenSp;
    }

    public String getDonViTinh() {
        return donViTinh;
    }

    public void setDonViTinh(String donViTinh) {
        this.donViTinh = donViTinh;
    }

    public float getGiaDv() {
        return giaDv;
    }

    public void setGiaDv(float giaDv) {
        this.giaDv = giaDv;
    }

    public Set getChiTietDonXuats() {
        return chiTietDonXuats;
    }

    public void setChiTietDonXuats(Set chiTietDonXuats) {
        this.chiTietDonXuats = chiTietDonXuats;
    }

    public Set getChiTietKhos() {
        return chiTietKhos;
    }

    public void setChiTietKhos(Set chiTietKhos) {
        this.chiTietKhos = chiTietKhos;
    }

    public Set getChiTietDonNhaps() {
        return chiTietDonNhaps;
    }

    public void setChiTietDonNhaps(Set chiTietDonNhaps) {
        this.chiTietDonNhaps = chiTietDonNhaps;
    }

    

}
